#!/bin/bash
echo "this script is from github"
NUMBER=$(($NUMBERONE + $NUMBERTWO))
echo "$NUMBER"
echo "This was added"
echo "This is to test"
echo "This is test again"
echo "it is not working"
echo "it is the time"
echo "last attempt"
echo "One more last attempt"
echo "second"
echo "third"
echo "forth"
echo "test"
echo "one more test to verify creds"
echo "checking cache featur"
echo "checking ssh keys"
